Repository EdwardKN/Sudoku, pull requests merged in 2023-03, with the labels that each got.

#21 Recursive
  index.html
  solver.js
  solver2.js
  visual.js
Labels: enhancement

#23 json och bort med solver1
  index.html
  solver.js
  solver2.js
  testpussel.json
  visual.js
Labels: enhancement

#22 undofix
  visual.js
Labels: bug

#26 piltangenter flyttar
  visual.js
Labels: enhancement

#30 28 ta bort fasta utsatta siffror
  visual.js
Labels: bug

#33 Fuskinställningar och nytt interface
  .vscode/settings.json
  index.html
  style.css
  visual.js
Labels: enhancement

#36 Update README.md
  README.md
Labels: documentation

#38 Smalfix
  visual.js
Labels: enhancement

#37 Update index.html
  index.html
Labels: documentation

#40 Generator
  generator.js
  index.html
  solver.js
  visual.js
Labels: enhancement

#42 sparar korrekt
  generator.js
  solver.js
Labels: bug

#43 bort med json
  .vscode/settings.json
  testpussel.json
  visual.js
Labels: clean unused

#44 kanske fixad loading
  visual.js
Labels: bug

#47 timer tillagd
  generator.js
  style.css
  visual.js
Labels: enhancement

#48 remove solve2 + hard
  generator.js
  solver.js
  visual.js
Labels: enhancement

#52 timer stannar
  visual.js
Labels: enhancement

#53 Leaderboard med troligtvis flera buggar
  solver.js
  style.css
  visual.js
Labels: enhancement

#55 lite buggfixar
  solver.js
  style.css
  visual.js
Labels: bug
